Condition.create(name: "新品、未使用")
Condition.create(name: "未使用に近い")
Condition.create(name: "目立った傷や汚れなし")
Condition.create(name: "やや傷や汚れあり")
Condition.create(name: "傷や汚れあり")
Condition.create(name: "全体的に状態が悪い")
