Size.create(name: "XXS以下")
Size.create(name: "XS(SS)")
Size.create(name: "S")
Size.create(name: "M")
Size.create(name: "L")
Size.create(name: "XL(LL)")
Size.create(name: "2XL(3L)")
Size.create(name: "3XL(4L)")
Size.create(name: "4XL(5L)以上")
Size.create(name: "FREE SIZE")
